config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :orders

  devise_for :restaurant_admins
  resources :restaurants

  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users, :only => [:show, :create, :update, :destroy]
      resources :sessions, :only => [:create, :destroy]
      resources :dishes
      resources :restaurants
      resources :dish_categories
      resources :restaurant_categories
      resources :orders, :only => [:create, :update, :destroy]
    end
  end

  get 'index/home'

  
  resources :dishes

  resources :dish_categories

  resources :restaurant_categories

  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  
   get '/static_pages/page_404' => 'static_pages#page_404'

  devise_scope :admin do
    get "admin/sign_in", to: "devise/sessions#new"
    root 'devise/sessions#new'
  end

end

app/models/restaurant_category.rb
class RestaurantCategory < ActiveRecord::Base
	validates :name, presence: true, length: {maximum: 20}

	rails_admin do 
		list do 
			field :name
			field :created_at
			field :updated_at
		end
	end
end

app/controllers/api/v1/restaurant_categories_controller.rb
class Api::V1::RestaurantCategoriesController < ApplicationController

  before_action :set_restaurant_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @restaurant_categories = RestaurantCategory.all
    respond_with(@restaurant_categories)
  end

  def show
    respond_with(@restaurant_category)
  end

  def new
    @restaurant_category = RestaurantCategory.new
    respond_with(@restaurant_category)
  end

  def edit
  end

 
   def create
    @restaurant_category = RestaurantCategory.new(restaurant_category_params)
    @restaurant_category.save
    respond_with(@restaurant_category)
  end

  def update
    @restaurant_category.update(restaurant_category_params)
    respond_with(@restaurant_category)
  end

  def destroy
    @restaurant_category.destroy
    respond_with(@restaurant_category)
  end

  private
    def set_restaurant_category
      @restaurant_category = RestaurantCategory.find(params[:id])
    end

    def restaurant_category_params
      params.require(:restaurant_category).permit(:name)
    end
end

app/helpers/restaurant_categories_helper.rb
module RestaurantCategoriesHelper
end

app/views/restaurant_categories/_form.html.erb
<%= form_for(@restaurant_category) do |f| %>
  <% if @restaurant_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant_category.errors.count, "error") %> prohibited this restaurant_category from being saved:</h2>

      <ul>
      <% @restaurant_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurant_categories/edit.html.erb
<h1>Editing Restaurant Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_category %> |
<%= link_to 'Back', restaurant_categories_path %>

app/views/restaurant_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurant Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurant_categories.each do |restaurant_category| %>
      <tr>
        <td><%= restaurant_category.name %></td>
        <td><%= link_to 'Show', restaurant_category %></td>
        <td><%= link_to 'Edit', edit_restaurant_category_path(restaurant_category) %></td>
        <td><%= link_to 'Destroy', restaurant_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant category', new_restaurant_category_path %>

app/views/restaurant_categories/new.html.erb
<h1>New Restaurant Category</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_categories_path %>

app/views/restaurant_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant_category.name %>
</p>

<%= link_to 'Edit', edit_restaurant_category_path(@restaurant_category) %> |
<%= link_to 'Back', restaurant_categories_path %>