config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :orders

  devise_for :restaurant_admins
  resources :restaurants

  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users, :only => [:show, :create, :update, :destroy]
      resources :sessions, :only => [:create, :destroy]
      resources :dishes
      resources :restaurants
      resources :dish_categories
      resources :restaurant_categories
      resources :orders, :only => [:create, :update, :destroy]
    end
  end

  get 'index/home'

  
  resources :dishes

  resources :dish_categories

  resources :restaurant_categories

  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  
   get '/static_pages/page_404' => 'static_pages#page_404'

  devise_scope :admin do
    get "admin/sign_in", to: "devise/sessions#new"
    root 'devise/sessions#new'
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  has_many   :order_details
  has_many   :dishes, through: :order_details
# 
  scope :open_orders, -> { where(active: true) }
  scope :closed_orders, -> { where(active: false) }

  # validates :user_id, :restaurant, presence: true
  # validates :table_no, numericality: { greater_than_or_equal_to: 0}, presence: true
  # validates :amount, numericality: {greater_than_or_equal_to: 0}, presence: true

  # def get_order
  # 	self.order_details
  # end

  def get_details
  	self.order_details
  end



  def username
  	"<a href='user/#{self.user.id}/'>#{self.user.first_name}</a>".html_safe
  end

	rails_admin do
		list do
			field :username
			field :amount
			# field :tax
			# field :tip
			field :table_no
			field :restaurant
	    end
	end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_with_token!
  respond_to :html
  respond_to :json
  
  def index
    # @orders = current_user.orders
    # respond_with(@orders)
    respond_with Order.all
  end

  #Need to add current_user

  def show
    # respond_with(@order)
    respond_with Order.find(params[:id])
  end

  def new
    @order = Order.new
    respond_with(@order)
  end

  def edit
  end

  # def create
  #   p params.to_yaml
  #   @order = Order.new(order_params)
  #   @order.save
  #   respond_with(@order)
  # end

  def create
    order = current_user.orders.build(order_params)
    if order.save
      render json: order, status: 201 location: [:api, order]
    else
      render json: { errors: order.errors }, status: 422
    end
  end

  # def update
  #   @order.update(order_params)
  #   respond_with(@order)
  # end 

  def update
    order = current_user.orders.find(params[:id])
    if order.update(order_params)
      render json: order, status: 200 location: [:api, order]
    else
      render json: { errors: order.errors }, status: 422
  end

  # def destroy
  #   @order.destroy
  #   respond_with(@order)
  # end

  def destroy
    order = current_user.orders.find(params[:id])
    order.destroy
    head 204
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:user_id, :user_name, :tax, :tip, :transaction_id, :table_no, :date_of_order, :active, :time_to_dispatch_order, :restaurant_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @orders = Order.all
    respond_with(@orders)
  end

  def show
    respond_with(@order)
  end

  def new
    @order = Order.new
    respond_with(@order)
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.save
    respond_with(@order)
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:amount, :tax, :tip, :transaction_id, :table_no, :time_to_dispatch_order, :dine_in, :restaurant_id, :user_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :amount %>
    <%= f.input :tax %>
    <%= f.input :tip %>
    <%= f.input :transaction_id %>
    <%= f.input :table_no %>
    <%= f.input :time_to_dispatch_order %>
    <%= f.input :dine_in %>
    <%= f.association :restaurant %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Tax</th>
      <th>Tip</th>
      <th>Transaction</th>
      <th>Table no</th>
      <th>Time to dispatch order</th>
      <th>Dine in</th>
      <th>Restaurant</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.amount %></td>
        <td><%= order.tax %></td>
        <td><%= order.tip %></td>
        <td><%= order.transaction_id %></td>
        <td><%= order.table_no %></td>
        <td><%= order.time_to_dispatch_order %></td>
        <td><%= order.dine_in %></td>
        <td><%= order.restaurant %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @order.tax %>
</p>

<p>
  <strong>Tip:</strong>
  <%= @order.tip %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @order.transaction_id %>
</p>

<p>
  <strong>Table no:</strong>
  <%= @order.table_no %>
</p>

<p>
  <strong>Time to dispatch order:</strong>
  <%= @order.time_to_dispatch_order %>
</p>

<p>
  <strong>Dine in:</strong>
  <%= @order.dine_in %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @order.restaurant %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>