config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :orders

  devise_for :restaurant_admins
  resources :restaurants

  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users, :only => [:show, :create, :update, :destroy]
      resources :sessions, :only => [:create, :destroy]
      resources :dishes
      resources :restaurants
      resources :dish_categories
      resources :restaurant_categories
      resources :orders, :only => [:create, :update, :destroy]
    end
  end

  get 'index/home'

  
  resources :dishes

  resources :dish_categories

  resources :restaurant_categories

  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  
   get '/static_pages/page_404' => 'static_pages#page_404'

  devise_scope :admin do
    get "admin/sign_in", to: "devise/sessions#new"
    root 'devise/sessions#new'
  end

end

app/models/dish_category.rb
class DishCategory < ActiveRecord::Base
	validates :name, presence: true, length: {maximum: 20}

	rails_admin do 
		list do
			field :name
			field :created_at
			field :updated_at
		end
	end
end

app/controllers/api/v1/dish_categories_controller.rb
class Api::V1::DishCategoriesController < ApplicationController

 
  before_action :set_dish_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_with_token!
  respond_to :html

  def index
    @dish_categories = DishCategory.all
    respond_with(@dish_categories)
  end

  def show
    respond_with(@dish_category)
  end

  def new
    @dish_category = DishCategory.new
    respond_with(@dish_category)
  end

  def edit
  end

  def create
    @dish_category = DishCategory.new(dish_category_params)
    @dish_category.save
    respond_with(@dish_category)
  end

  def update
    @dish_category.update(dish_category_params)
    respond_with(@dish_category)
  end

  def destroy
    @dish_category.destroy
    respond_with(@dish_category)
  end

  private
    def set_dish_category
      @dish_category = DishCategory.find(params[:id])
    end

    def dish_category_params
      params.require(:dish_category).permit(:name)
    end
end

app/helpers/dish_categories_helper.rb
module DishCategoriesHelper
end

app/views/dish_categories/_form.html.erb
<%= form_for(@dish_category) do |f| %>
  <% if @dish_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish_category.errors.count, "error") %> prohibited this dish_category from being saved:</h2>

      <ul>
      <% @dish_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dish_categories/edit.html.erb
<h1>Editing Dish Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish_category %> |
<%= link_to 'Back', dish_categories_path %>

app/views/dish_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dish Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dish_categories.each do |dish_category| %>
      <tr>
        <td><%= dish_category.name %></td>
        <td><%= link_to 'Show', dish_category %></td>
        <td><%= link_to 'Edit', edit_dish_category_path(dish_category) %></td>
        <td><%= link_to 'Destroy', dish_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish category', new_dish_category_path %>

app/views/dish_categories/new.html.erb
<h1>New Dish Category</h1>

<%= render 'form' %>

<%= link_to 'Back', dish_categories_path %>

app/views/dish_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish_category.name %>
</p>

<%= link_to 'Edit', edit_dish_category_path(@dish_category) %> |
<%= link_to 'Back', dish_categories_path %>