config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :orders

  devise_for :restaurant_admins
  resources :restaurants

  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users, :only => [:show, :create, :update, :destroy]
      resources :sessions, :only => [:create, :destroy]
      resources :dishes
      resources :restaurants
      resources :dish_categories
      resources :restaurant_categories
      resources :orders, :only => [:create, :update, :destroy]
    end
  end

  get 'index/home'

  
  resources :dishes

  resources :dish_categories

  resources :restaurant_categories

  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  
   get '/static_pages/page_404' => 'static_pages#page_404'

  devise_scope :admin do
    get "admin/sign_in", to: "devise/sessions#new"
    root 'devise/sessions#new'
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :restaurant_admin
  belongs_to :restaurant_category

  has_many  :table_management
  accepts_nested_attributes_for :table_management
	has_many :dishes
	has_many :orders
  belongs_to :user

  validate :validate_available_from, :validate_available_from_equality
  validate :validate_from_time
  

	accepts_nested_attributes_for :dishes, allow_destroy: true
	# has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"


#Content uploading to S3 Bucket
  has_attached_file  :image,
                     :styles =>  {:medium => "300x300", :thumb => "100x100"},
                     :storage => :s3,
                     :s3_credentials => S3_CONFIG,
                     :bucket => APP_CONFIG["bucket"],
                     :default_url => ":s3_domain_url",
                     :preserve_files => true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

#Adding logo to S3 Bucket
  has_attached_file  :restaurant_logo,
                     :styles =>  {:medium => "300x300", :thumb => "100x100"},
                     :storage => :s3,
                     :s3_credentials => S3_CONFIG,
                     :bucket => APP_CONFIG["bucket"],
                     :default_url => ":s3_domain_url",
                     :preserve_files => true
  validates_attachment_content_type :restaurant_logo, :content_type => /\Aimage\/.*\Z/

# Validations
 
         # validates :restaurant_name, presence: true, length: {maximum: 20}
         # validates :restaurant_category, presence: true
         # validates :restaurant_admin, presence: true
         # validates :image, presence: true
         # validates :address1, presence: true, length: {maximum: 50}
         # validates :address2, presence: true, length: {maximum: 50}
         # validates :description, presence: true, length: {maximum: 1000}
         # validates :country, presence: true
         # validates :countrycode, presence: true, :numericality => true
         # validates :city, presence: true
         # validates :location, presence: true
         # validates :latitude, presence: true, :numericality => true
         # validates :longitude, presence: true, :numericality => true
         # validates :city, presence: true, length: {maximum: 20}
         # validates :no_of_tables, presence: true, numericality: { greater_than_or_equal_to: 0 }
         # validates :from_time, presence: true
         # validates :to_time, presence: true
         # validates :available_from, presence: true
         # validates :available_to, presence: true
         # validates :dining_cost_rating, presence: true
         # validates :tax, presence: true, numericality: { greater_than_or_equal_to: 0 }
         # validates :available_from, presence: true
         # validates :available_to, presence: true
         # validates :from_time, presence: true
         # validates :to_time, presence: true


#Custom validation goes here------------------------
           

   def validate_available_from
     if available_from.present? && available_to < available_from
       errors.add(:available_to, "can't be  past")
     end
   end

   def validate_available_from_equality
     if available_from.present? && available_to == available_from
      errors.add(:available_to, "can't be equal")
    end
  end

    def validate_from_time
      if from_time.present? && from_time > to_time
        errors.add(:to_time, "can't be past")
      end
    end

    
   # def validate_from_time
   #  if from_time.strftime.present? && from_time.strftime < to_time.strftime
   #    errors.add(:to_time, "can't be less than")
   #  end

    # def validate_from_time_equality
    #   if from_time.present? && from_time == to_time
    #     errors.add(:to_time, "can't be equal")
    #   end
    # end


 

  def restaurant_link
    "<a href='restaurant/#{self.id}/'>#{self.restaurant_name}</a>".html_safe
  end

  def from_time
    if self.available_from.present?
        temp_time = self.available_from.to_s.split(':')     
        Time.parse("#{temp_time[0]}:#{temp_time[1]}").strftime("%l %P")
    end
  end

  def to_time
    if self.available_to.present?
       temp_time = self.available_to.to_s.split(':')
       Time.parse("#{temp_time[0]}:#{temp_time[1]}").strftime("%l %P")
   	end
  end

  def name
		self.restaurant_name
	end
 
 # def dining_cost_rating_enum
 #   # [['Active', 1],['Pending',0],['Banned',2]]
 #   [['Active'],['Pending'],['Banned']]
 # end
  
  def get_orders
    self.orders.open_orders
  end

  def get_closed_orders
    self.orders.closed_orders
  end

#For listing dishes inside the restaurant 
  def get_dishes
    self.dishes  
  end



  

 	rails_admin do
      list do
          field :restaurant_link do
              label "RestaurantName"
          end
          field :restaurant_category
          field :no_of_tables
          field :from_time do
            label "Opening Time"
          end

          field :to_time do 
            label "Closing Time"
          end
          field :country 
          field :tax do 
            label "Restaurant Tax"
          end
      end

      edit do
         field :restaurant_name do 
            label "Restaurant Name"
          end
         field :image
         field :restaurant_logo do 
          label "Restaurant Logo"
         end
         field :short_Address
         field :long_Address
         field :description
         field :restaurant_admin do
          label "Restaurant Admin"
        end
         field :no_of_tables do
          label "No of Tables"
        end

         field :dining_cost_rating, :enum do 
            label "Dining Cost Rating"
            enum do
               %w(1 2 3 4)
            end
         end
         
         field :tax do
          label "Restaurant Tax"
        end
         field :restaurant_category do 
           label "Restaurant Category"
         end
         field :dishes 
         field :table_management do
          label "Manage Table"
        end

         field :country 
         field :countrycode do 
           label "Country Code"
         end
         field :city
         # field :location
         field :latitude
         field :longitude
         field :from_time do 
          label "Opening Time"
        end
         field :to_time do 
           label "Closing Time"
         end
         field :available_from do
          label "Active From"
         end
         field :available_to do
          label "Active To"
         end
         field :active
      end
  end
end

app/controllers/api/v1/restaurants_controller.rb
class Api::V1::RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  respond_to :html
  respond_to :json

  def index
    @restaurants = Restaurant.all
    respond_with(@restaurants)
  end

  def show
    respond_with(@restaurant)
  end

  def new
    @restaurant = Restaurant.new
    respond_with(@restaurant)
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    respond_with(@restaurant)
  end

  def update
    @restaurant.update(restaurant_params)
    respond_with(@restaurant)
  end

  def destroy
    @restaurant.destroy
    respond_with(@restaurant)
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:restaurant_name, :description, :available_from, :available_to, :no_of_tables, :email, :address1, :address2, :country, :countrycode, :location, :city, :phonenumber, :latitude, :longitude, :admin_id, :restaurant_category_id, :active)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :restaurant_name %>
    <%= f.input :description %>
    <%= f.input :available_from %>
    <%= f.input :available_to %>
    <%= f.input :no_of_tables %>
    <%= f.input :email %>
    <%= f.input :address1 %>
    <%= f.input :address2 %>
    <%= f.input :country %>
    <%= f.input :countrycode %>
    <%= f.input :location %>
    <%= f.input :city %>
    <%= f.input :phonenumber %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.association :admin %>
    <%= f.association :restaurant_category %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant name</th>
      <th>Description</th>
      <th>Available from</th>
      <th>Available to</th>
      <th>No of tables</th>
      <th>Email</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>Country</th>
      <th>Countrycode</th>
      <th>Location</th>
      <th>City</th>
      <th>Phonenumber</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Admin</th>
      <th>Restaurant category</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.restaurant_name %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.available_from %></td>
        <td><%= restaurant.available_to %></td>
        <td><%= restaurant.no_of_tables %></td>
        <td><%= restaurant.email %></td>
        <td><%= restaurant.address1 %></td>
        <td><%= restaurant.address2 %></td>
        <td><%= restaurant.country %></td>
        <td><%= restaurant.countrycode %></td>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.city %></td>
        <td><%= restaurant.phonenumber %></td>
        <td><%= restaurant.latitude %></td>
        <td><%= restaurant.longitude %></td>
        <td><%= restaurant.admin %></td>
        <td><%= restaurant.restaurant_category %></td>
        <td><%= restaurant.active %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant name:</strong>
  <%= @restaurant.restaurant_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Available from:</strong>
  <%= @restaurant.available_from %>
</p>

<p>
  <strong>Available to:</strong>
  <%= @restaurant.available_to %>
</p>

<p>
  <strong>No of tables:</strong>
  <%= @restaurant.no_of_tables %>
</p>

<p>
  <strong>Email:</strong>
  <%= @restaurant.email %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @restaurant.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @restaurant.address2 %>
</p>

<p>
  <strong>Country:</strong>
  <%= @restaurant.country %>
</p>

<p>
  <strong>Countrycode:</strong>
  <%= @restaurant.countrycode %>
</p>

<p>
  <strong>Location:</strong>
  <%= @restaurant.location %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @restaurant.phonenumber %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @restaurant.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @restaurant.longitude %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @restaurant.admin %>
</p>

<p>
  <strong>Restaurant category:</strong>
  <%= @restaurant.restaurant_category %>
</p>

<p>
  <strong>Active:</strong>
  <%= @restaurant.active %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>